// Sometimes when you use mongoose with testing framework it will complain if you call in a model multiple times
const mongoose = require('mongoose')

const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');

// Added for testing framework scalability
const Survey = mongoose.model('surveys');

module.exports = app => {
    // 2 things to vet about user before hooking up.
    // first user needs to be logged in and authenticated - use middleware 
    // second that user has enough credits 
    app.post('/api/surveys', requireLogin, requireCredits, (req, res) => {
        const { title, subject, body, recipients } = req.body;

         // Model class creates an instance of a survey and not persisted to the database...to save it, gotta call save()
         // Sub-Document collection of recipients - array of objects containing users email with responded property defaulting to false
        //    Take list of emails and use split to give us an array of strings and then map over it to assign in a object
        const survey = new Survey({
            title: title, //ES6 can reduce it down to just title
            subject: subject,
            body: body,
            recipients: recipients.split(',').map(email => { return { email: email }}),
            _user: req.user.id,
            dateSent: Date.now() 
        })
    })
};
// ES6 Reduces to = recipients: recipients.split(',').map(email => ({ email })
// _user: req.user.id - The id is automatically generated by mongoose model